import { writeFileSync } from "fs";
import { relative } from "path";
import { Report, getStatusIcon } from "./reportBuilder";
import { Finding } from "../models/types";

const SECTIONS: { title: string; type: Finding["type"] }[] = [
  { title: "Dead Code", type: "dead-code" },
  { title: "Long Files", type: "long-file" },
  { title: "Similar Code", type: "similar-code" },
  { title: "Deep Complexity", type: "deep-complexity" },
];

function shortPath(filePath: string): string {
  const cwd = process.cwd();
  return relative(cwd, filePath).replace(/\\/g, "/");
}

export function generateMarkdown(
  report: Report,
  outputPath: string,
  version: string
): void {
  const lines: string[] = [];
  const icon = getStatusIcon(report.entropy);
  const { summary } = report;

  lines.push("# \uD83E\uDDEC Repo Entropy Report\n");
  lines.push(
    `> Generated by [repo-entropy](https://github.com/user/repo-entropy) v${version}\n`
  );

  lines.push("## Summary\n");
  lines.push("| Metric | Value |");
  lines.push("|--------|-------|");
  lines.push(`| Files Analyzed | ${summary.totalFiles} |`);
  lines.push(`| Entropy Score | **${report.entropy} / 100** |`);
  lines.push(`| Status | ${icon} ${report.status} |`);
  lines.push(`| Dead Code Issues | ${summary.deadCode} |`);
  lines.push(`| Long File Issues | ${summary.longFiles} |`);
  lines.push(`| Similar Code Issues | ${summary.similarCode} |`);
  lines.push(`| Deep Complexity Issues | ${summary.deepComplexity} |`);
  lines.push("");

  for (const section of SECTIONS) {
    const items = report.findings.filter((f) => f.type === section.type);
    lines.push(`## ${section.title}\n`);

    if (items.length === 0) {
      lines.push("No issues found.\n");
    } else {
      for (const item of items) {
        lines.push(`- \`${shortPath(item.file)}\` \u2014 ${item.message}`);
      }
      lines.push("");
    }
  }

  lines.push("---\n");
  lines.push(buildFixPrompt(report));
  lines.push("---\n");
  lines.push(
    "*Tip: Run `repo-entropy analyze .` periodically to track entropy over time.*\n"
  );

  writeFileSync(outputPath, lines.join("\n"), "utf-8");
}

function buildFixPrompt(report: Report): string {
  const lines: string[] = [];

  lines.push("## AI Fix Prompt\n");
  lines.push(
    "> Copy the prompt below into your IDE assistant (Cursor, Copilot, etc.) to start fixing these issues.\n"
  );

  const promptLines: string[] = [];
  promptLines.push(
    "Analyze and fix the following code entropy issues detected in this repository.\n"
  );

  let hasIssues = false;

  for (const section of SECTIONS) {
    const items = report.findings.filter((f) => f.type === section.type);
    if (items.length === 0) continue;
    hasIssues = true;

    promptLines.push(`**${section.title} (${items.length} issues)**\n`);
    const topItems = items.slice(0, 10);
    for (const item of topItems) {
      promptLines.push(`- ${shortPath(item.file)} \u2014 ${item.message}`);
    }
    if (items.length > topItems.length) {
      promptLines.push(`- ...and ${items.length - topItems.length} more`);
    }
    promptLines.push("");
  }

  if (!hasIssues) {
    lines.push("No issues to fix \u2014 your codebase is clean!\n");
    return lines.join("\n");
  }

  promptLines.push("Fix each issue one at a time. For each fix:");
  promptLines.push("1. Show the current problematic code");
  promptLines.push("2. Explain why it is an issue");
  promptLines.push("3. Provide the corrected code");
  promptLines.push("4. Verify no regressions are introduced\n");
  promptLines.push("Start with the highest-severity issues first.\n");

  lines.push("```text");
  lines.push(promptLines.join("\n"));
  lines.push("```\n");

  return lines.join("\n");
}
